### PR TITLE
removed wip doc

### PR DESCRIPTION
**Pull request by jotadepicas**

### CODE REVIEW

**Comment by tjanczuk** [comment]
There are links to this file in the main readme, can you also remove them? Or better yet, remove the link int he main readme file *without* removing the file. THis is the only remaining form of documentation (apart from code).

**Comment by jotadepicas** [comment]
oops, totally, sorry I missed them, will take care of it now.

**Comment by jotadepicas** [comment]
however I think I'll be removing the file so no one can find it in the repo and try to follow it. It can be tempting to follow it, no matter if it's linked or not, what do you think.

**Comment by tjanczuk** [comment]
I think the risk of that close to zero. If someone is determined enough they can reverse-engineer this from code. I'd leave it in.

**Comment by jotadepicas** [comment]
fair enough, recovered the deleted file. Just removed the links from main readme.

**Comment by jotadepicas** [comment]
@tjanczuk hi there, going though open PRs, this still needs merge, right?

**Comment by jhiner** [comment]
Should be closed in favor of #12

**Comment by ggoodman** [comment]
Replaced by #12

**Pull request closed without merging**
