### PR TITLE
Configuring compiler for post-password-change

### PR DESCRIPTION
**Pull request by sgmeyer**
Post Change Password utilizes the same compiler as user registration.  For now we will use the same compiler until it requires further change.

### CODE REVIEW

**Comment by sandrinodimattia** [comment]
I would suggest duplicating it. These are different features, code reuse here does not make sense and when we make changes to user registration we don't want these to end up in password change (eg: adding more data to the user registration hook)

Or at least renaming the user registration compile to something else then. It's not clear by looking at the structure/code that this is also being reused for post password change.

**Comment by tjanczuk** [comment]
We are already using the same code for `post-` and `pre-user-registration`, adding one more use case does not change how this code is factored. I am fine with adding one more name to the same piece of code, and only make a copy if/when when actual differences materialize. 

Please update version in package.json.

**Comment by sgmeyer** [comment]
@tjanczuk and @sandrinodimattia thanks for the feedback.  I went with this approach after chatting with @ggoodman.  Initially, I went in the direction @sandrinodimattia mentioned, but settled on this approach.  I went ahead and bumped the minor version number.  Let me know if there is anything else needed.

**Comment by tjanczuk** [comment]
@sgmeyer added some tests, published to NPM as 5.5.0

**Pull request merged**
